version: '3'
services:
  database:
   build: .
   container_name: database
   ports:
     - "3306:3306"
   volumes:
    - "~/mysql/datadir:/var/lib/mysql"
    - "~/mysql/my.cnf:/etc/my.cnf"
networks:
      default:
        external:
          name: project221
